function writeQuotationPdf(doc, quotation) {
  doc.fontSize(20).text("Fire Safety Quotation", { align: "center" });
  doc.moveDown();

  doc.fontSize(12);
  doc.text(`Quotation ID: ${quotation.id}`);
  doc.text(`Project Name: ${quotation.projectName}`);
  doc.text(`Date: ${new Date(quotation.createdAt).toLocaleDateString()}`);
  doc.moveDown();

  doc.fontSize(15).text("Cost Summary");
  doc.moveDown(0.5);
  doc.fontSize(12);
  doc.text(`Equipment Cost: ${quotation.equipmentCost}`);
  doc.text(`Installation Cost: ${quotation.installationCost}`);
  doc.text(`Maintenance Cost: ${quotation.maintenanceCost}`);
  doc.text(`GST: ${quotation.gst}`);
  doc.moveDown();
  doc.fontSize(14).text(`Total Cost: ${quotation.totalCost}`, {
    underline: true,
  });

  doc.moveDown(2);
  doc.fontSize(10).text("Generated by Fire Safety Planning Quotation System", {
    align: "center",
  });
}

module.exports = {
  writeQuotationPdf,
};
